name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Backend
      - name: Install Backend Dependencies
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            npm ci
            npm test || echo "No tests found"
          fi

      # Frontend
      - name: Install Frontend Dependencies
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm ci
            npm run build || echo "No build script found"
          fi

                # -------------------
      # Docker Build + Trivy Scan
      # -------------------
      - name: Build Docker image for backend
        if: ${{ hashFiles('backend/Dockerfile') != '' }}
        run: |
          cd backend
          docker build -t securepayment-backend .

      - name: Scan Docker image with Trivy
        if: ${{ hashFiles('backend/Dockerfile') != '' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: securepayment-backend
          format: 'table'
          exit-code: '0' # Set to '1' to fail build on vulnerabilities
          vuln-type: 'os,library'

